language: go

go:
  - 1.7

sudo: required
services:
  - docker

before_install:
  - go get github.com/karalabe/xgo

script:
  - make check
  - docker pull karalabe/xgo-latest
  - mkdir dist
  - cd dist
  - xgo -go 1.7.x -v --targets='windows/*,darwin/*,linux/*' github.com/igrybkov/leosync
